### ISSUE TITLE
No license of use

### ISSUE THREAD

**Issue by giulianob** [gsamokovarov/gloat#2]
@gsamokovarov Would it be possible to add a license to this project?

**Comment by gsamokovarov** [comment]
Oh, sorry about that. Will add the MIT License in a bit.

**Comment by gsamokovarov** [comment]
@giulianob, I have put the repo under MIT. Please, tell me if you like or need anything from the project. For sure, we'll benefit from better documentation, so if you have trouble using it, don't hesitate to reach out.

✌️
